server {
    listen 443 ssl;
    server_name cashhero.example.com;

    root /data/web;
    index index.html;
    ssl_certificate     /etc/openresty/ssl/freefree.vip.pem;
    ssl_certificate_key /etc/openresty/ssl/freefree.vip.key;

    location / {
        try_files $uri $uri/ /index.html;
    }
}